### ISSUE TITLE
Cannot find module '../util/plist-helpers'

### ISSUE THREAD

**Issue by lukas2** [apache/cordova-ios#986]
# Bug Report

## Problem

After bumping cordova-ios from 6.1.0 to 6.1.1 installation of plugins fails:
```
Failed to install 'cordova-plugin-firebasex': Error: Cannot find module '../util/plist-helpers'
```

### What is expected to happen?

Installation succeeds.

### What does actually happen?

Error `Cannot find module '../util/plist-helpers'`

## Information

This seems to have something to do with cordova-common being bumped from 4.0.1 to 4.0.2 but I can't find the issue.

(If it helps, our path does include Whitespace, my gut tells me it _might_ be related to https://github.com/apache/cordova-ios/issues/984 but who knows..)

### Environment, Platform, Device

mac OS Catalina, 10.15.6

### Version information

Cordova CLI: 9.0.0 also tried 10.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
You might try to do a clean setup. For example, delete from the project directory:

* `node_modules` directory
* `package-lock.json` file

Then run `npm i` to re-checkout everything that is in the `package.json`...

**Comment by lukas2** [comment]
I am closing this because there was a problem with our build script. It specified a version with `cordova platform add ..`
