### ISSUE TITLE
Error in cordova prepare when update cordova-ios from 6 to 7.

### ISSUE THREAD

**Issue by DiegoSestito** [apache/cordova-ios#1398]
# Bug Report

## Problem
When running cordova prepare I get the following error: 
##[error]Searching for inspections failed: undefined method `map' for nil:NilClass

##[error]Command failed with exit code 1: pod install --verbose

### What is expected to happen?
command successfully executed

### What does actually happen?
command fail

## Information
I've already tried the suggested solution of running the script: sudo arch -x86_64 gem install ffi

### Command or Code
cordova prepare ios

### Environment, Platform, Device
Start after updating cordova-ios from 6 to 7.

### Version information
cordova 12
cordova-ios 7
macos 13

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
Can you try running `cordova requirements` and post the output here?

How did you install CocoaPods? It sounds like this issue can happen if you did something like `sudo gem install cocoapods` and one suggested workaround is to install CocoaPods using a package manager like Homebrew

**Comment by dpogue** [comment]
Closing due to lack of response.
