### ISSUE TITLE
Investigate & Fix Test with Jasmine@^3.2.0

### ISSUE THREAD

**Issue by erisu** [apache/cordova-ios#393]
# Overview
With the recent release of `jasmine@3.2.0`, two of the tests have begun to fail.

# The Goal
- Investigate if the test failures are caused by our tests or a bug introduced by Jasmine.
- If the issue is caused by our tests, the tests should be updated to work with `jasmine@3.2.0`.

# Error Log
```
Suite error: Platform Api .prototype addPlugin
  Message:
    TypeError: plugin.getFrameworks is not a function
  Stack:
        at <Jasmine>
        at /Users/travis/build/apache/cordova-ios/bin/templates/scripts/cordova/Api.js:106:414
        at _fulfilled (/Users/travis/build/apache/cordova-ios/node_modules/q/q.js:854:54)
        at /Users/travis/build/apache/cordova-ios/node_modules/q/q.js:883:30
        at Promise.promise.promiseDispatch (/Users/travis/build/apache/cordova-ios/node_modules/q/q.js:816:13)
        at /Users/travis/build/apache/cordova-ios/node_modules/q/q.js:877:14
        at runSingle (/Users/travis/build/apache/cordova-ios/node_modules/q/q.js:137:13)
        at flush (/Users/travis/build/apache/cordova-ios/node_modules/q/q.js:125:13)
        at process._tickCallback (internal/process/next_tick.js:61:11)
Suite error: cordova/lib/list-devices run method
  Message:
    TypeError: Cannot read property 'forEach' of undefined
  Stack:
        at <Jasmine>
        at /Users/travis/build/apache/cordova-ios/bin/templates/scripts/cordova/lib/list-devices:40:17
        at _fulfilled (/Users/travis/build/apache/cordova-ios/node_modules/q/q.js:854:54)
        at /Users/travis/build/apache/cordova-ios/node_modules/q/q.js:883:30
        at Promise.promise.promiseDispatch (/Users/travis/build/apache/cordova-ios/node_modules/q/q.js:816:13)
        at /Users/travis/build/apache/cordova-ios/node_modules/q/q.js:877:14
        at runSingle (/Users/travis/build/apache/cordova-ios/node_modules/q/q.js:137:13)
        at flush (/Users/travis/build/apache/cordova-ios/node_modules/q/q.js:125:13)
        at process._tickCallback (internal/process/next_tick.js:61:11)
```

* Travis CI: https://travis-ci.org/apache/cordova-ios/builds/414458809
* AppVeyor: https://ci.appveyor.com/project/Humbedooh/cordova-ios/build/1.0.745

# Recent Reported Issues
Below is a list of reported issues with jasmine@3.2.0. These can be used to identify if our test issues are related.

- https://github.com/jasmine/jasmine/issues/1590
